AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*'
  RunRailsCops: true

Metrics/AbcSize:
  Max: 28

Metrics/MethodLength:
  Max: 17

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
