language: ruby
rvm:
  - "2.2.0-preview1"
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate
script: xvfb-run bundle exec rspec spec/features && xvfb-run bundle exec rspec spec
