language: ruby
rvm:
  - "2.2.0-preview1"
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create:all db:migrate db:migrate_db2
script: xvfb-run bundle exec rspec spec
