development:
  adapter: postgresql
  encoding: unicode
  database: app3_development
  pool: 10
  username: app3
  password: app3

test:
  adapter: postgresql
  encoding: unicode
  database: app3_test
  pool: 5
  username: app3
  password: app3

production:
  adapter: postgresql
  encoding: unicode
  database: app3_production
  pool: 5
  username: app3
  password:
